### ISSUE TITLE
Look into what needs to happen to support the `pkg:` import syntax

### ISSUE THREAD

**Issue by wkillerud** [wkillerud/some-sass#108]
See [Sass announcement of the feature](https://sass-lang.com/blog/announcing-pkg-importers/)

> No longer will you have to manually add node_modules to your loadPaths option and worry about whether nested packages will work at all. No longer will you need to add ~s to your URLs and give up all portability. Now you can just pass `importers: [new NodePackageImporter()]` and write `@use 'pkg:library'` and it’ll work just how you want out of the box.

##  TODO

- [x] Set up a test project in [fixtures/](https://github.com/wkillerud/vscode-scss/tree/main/fixtures) ([branch: `pkg-import`](https://github.com/wkillerud/vscode-scss/tree/pkg-import/fixtures/e2e/pkg-import))
- [x] See how the new syntax affects [the parser and how it handles links](https://github.com/wkillerud/vscode-scss/blob/1cf9e61ea81356dab47b3b0c6444f1902638c2cb/server/src/parser/parser.ts#L67)
- [x] See how the new syntax affects import completions
- [x] See if it makes sense to use the official [importer via the JS API](https://sass-lang.com/documentation/js-api/classes/nodepackageimporter/)

**Comment by wkillerud** [comment]
> See how the new syntax affects the parser and how it handles links

Poorly. The parser doesn't register them as links. It also breaks Cmd+click to navigate, which is provided by vscode-css-languageservices (an issue is open in https://github.com/microsoft/vscode-css-languageservice/issues/383). Might be best to land support for this upstream, rather than patching it in here.

> See how the the import completion is affected by the new import syntax

Also poorly, but this one [is on me](https://github.com/wkillerud/vscode-scss/blob/main/server/src/features/completion/import-completion.ts).

**Comment by wkillerud** [comment]
> See if it makes sense to use the official [importer via the JS API](https://sass-lang.com/documentation/js-api/classes/nodepackageimporter/)

There's a [canonicalize method](https://github.com/sass/dart-sass/blob/3e6721e79f049dd01880542667380640c2d1eeae/lib/src/importer/node_package.dart#L37) that looked promising, but it's not part of the public API.
